esphome:
  name: esp8266sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266Sensor Fallback Hotspot"
    password: "b5ex5beNEQvO"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80


display:
#  -  platform: TM1637
#     id: tm1637_display
#     clk_pin: D6
#     dio_pin: D5
#     intensity: !lambda return id(brightness_value).state;
    
    
sensor:
  - platform: ultrasonic
    trigger_pin: D4
    echo_pin: D3
    update_interval: 5s
    name: "Ultrasonic Sensor"

  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s