esphome:
  name: esp8266
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_psk

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp8266 Fallback Hotspot"
    password: "bzw7ku8NIri8"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

switch:
  - platform: gpio
    name: "RED LED"
    pin:
      number: 4
      inverted: no

  - platform: gpio
    name: "YELLOW LED"
    pin:
      number: 14
      inverted: no

  - platform: gpio
    name: "GREEN LED"
    pin:
      number: 12
      inverted: no

binary_sensor:
  - platform: gpio
    pin: D7
    name: "PIR Sensor"
    device_class: motion

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 60s
